"""Updated Models

Revision ID: d743dee220f7
Revises: 2ba6c5448989
Create Date: 2020-11-22 14:31:45.179096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd743dee220f7'
down_revision = '2ba6c5448989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'date_of_birth')
    op.add_column('order', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('order', 'name_long')
    op.drop_column('order', 'name_short')
    op.drop_column('order', 'molecules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('molecules', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('name_short', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('name_long', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('order', 'name')
    op.drop_column('order', 'description')
    op.add_column('customer', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
