"""simplified order model

Revision ID: ef242aa7dd17
Revises: d743dee220f7
Create Date: 2020-11-22 16:02:31.162751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef242aa7dd17'
down_revision = 'd743dee220f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
